name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # จะทำงานทุกครั้งที่ push ไป branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t ygevo/api-nba:latest .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to Docker Hub
        run: docker push ygevo/api-nba:latest
